version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freelance_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:80"  # 80 в контейнере, 3000 для доступа снаружи
    depends_on:
      - server

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freelance_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d freelance_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: